- name: Configure Access Switches (Corrected Interface Numbers)
  hosts: access
  gather_facts: no
  vars_files:
    - vars/customers.yml
  
  tasks:
    - name: Clear existing VLAN assignments
      raw: |
        configure terminal
        default interface range FastEthernet1/0-15
        exit
        write memory

    - name: Configure Server Access Switch (access-sw1)
      raw: |
        configure terminal
        ! Create VLANs first
        vlan 100
        name CustomerA-WEB-SERVERS
        vlan 101
        name CustomerA-APP-SERVERS
        vlan 102
        name CustomerA-DB-SERVERS
        vlan 200
        name CustomerB-WEB-SERVERS
        vlan 201
        name CustomerB-APP-SERVERS
        vlan 202
        name CustomerB-DB-SERVERS
        
        ! Configure access ports
        interface range FastEthernet1/0-2
        description "CustomerA Web Servers"
        switchport mode access
        switchport access vlan 100
        spanning-tree portfast
        no shutdown
        
        interface range FastEthernet1/3-5
        description "CustomerA App Servers"
        switchport mode access
        switchport access vlan 101
        spanning-tree portfast
        no shutdown
        
        interface range FastEthernet1/6-8
        description "CustomerA DB Servers"
        switchport mode access
        switchport access vlan 102
        spanning-tree portfast
        no shutdown
        
        interface range FastEthernet1/9-11
        description "CustomerB Web Servers"
        switchport mode access
        switchport access vlan 200
        spanning-tree portfast
        no shutdown
        
        interface range FastEthernet1/12-13
        description "CustomerB App/DB Servers"
        switchport mode access
        switchport access vlan 201
        spanning-tree portfast
        no shutdown
        
        ! Trunk to distribution switch
        interface FastEthernet1/14
        description "Trunk to dist1-sw"
        switchport mode trunk
        switchport trunk allowed vlan 100,101,102,200,201,202
        no shutdown
        
        exit
        write memory
      when: inventory_hostname == 'access-sw1'

    - name: Configure User Access Switch (access-sw2)
      raw: |
        configure terminal
        ! Create VLANs
        vlan 109
        name CustomerA-USERS
        vlan 209
        name CustomerB-USERS
        
        ! Configure access ports
        interface range FastEthernet1/0-6
        description "CustomerA Users"
        switchport mode access
        switchport access vlan 109
        spanning-tree portfast
        no shutdown
        
        interface range FastEthernet1/7-13
        description "CustomerB Users"
        switchport mode access
        switchport access vlan 209
        spanning-tree portfast
        no shutdown
        
        ! Trunk to distribution switch
        interface FastEthernet1/14
        description "Trunk to dist1-sw"
        switchport mode trunk
        switchport trunk allowed vlan 109,209
        no shutdown
        
        exit
        write memory
      when: inventory_hostname == 'access-sw2'

    - name: Configure Server Access Switch (access-sw3)
      raw: |
        configure terminal
        ! Create VLANs
        vlan 300
        name CustomerC-WEB-SERVERS
        vlan 301
        name CustomerC-APP-SERVERS
        vlan 302
        name CustomerC-DB-SERVERS
        
        ! Configure access ports
        interface range FastEthernet1/0-2
        description "CustomerC Web Servers"
        switchport mode access
        switchport access vlan 300
        spanning-tree portfast
        no shutdown
        
        interface range FastEthernet1/3-5
        description "CustomerC App Servers"
        switchport mode access
        switchport access vlan 301
        spanning-tree portfast
        no shutdown
        
        interface range FastEthernet1/6-8
        description "CustomerC DB Servers"
        switchport mode access
        switchport access vlan 302
        spanning-tree portfast
        no shutdown
        
        ! Trunk to distribution switch
        interface FastEthernet1/14
        description "Trunk to dist2-sw"
        switchport mode trunk
        switchport trunk allowed vlan 300,301,302
        no shutdown
        
        exit
        write memory
      when: inventory_hostname == 'access-sw3'

    - name: Configure User Access Switch (access-sw4)
      raw: |
        configure terminal
        ! Create VLANs
        vlan 309
        name CustomerC-USERS
        
        ! Configure access ports
        interface range FastEthernet1/0-13
        description "CustomerC Users"
        switchport mode access
        switchport access vlan 309
        spanning-tree portfast
        no shutdown
        
        ! Trunk to distribution switch
        interface FastEthernet1/14
        description "Trunk to dist2-sw"
        switchport mode trunk
        switchport trunk allowed vlan 309
        no shutdown
        
        exit
        write memory
      when: inventory_hostname == 'access-sw4'

    - name: Verify Configuration Applied
      raw: show interfaces status
      register: interface_status
      
    - name: Display Interface Status
      debug:
        msg: |
          ===== {{ inventory_hostname }} Interface Status =====
          {{ interface_status.stdout }}
