- name: Configure Distribution Switches
  hosts: distribution
  gather_facts: no
  vars_files:
    - vars/customers.yml
  
  tasks:
    - name: Create Customer VLANs
      raw: |
        configure terminal
        {% for customer in customers %}
        {% if (customer.location == 'dist1' and inventory_hostname == 'dist1-sw') or (customer.location == 'dist2' and inventory_hostname == 'dist2-sw') %}
        ! {{ customer.name }} VLANs
        vlan {{ customer.vlans.web }}
        name {{ customer.name }}-WEB-SERVERS
        vlan {{ customer.vlans.app }}
        name {{ customer.name }}-APP-SERVERS  
        vlan {{ customer.vlans.db }}
        name {{ customer.name }}-DB-SERVERS
        vlan {{ customer.vlans.users }}
        name {{ customer.name }}-USERS
        {% endif %}
        {% endfor %}
        exit
        write memory

    - name: Configure SVI Gateway Interfaces
      raw: |
        configure terminal
        {% for customer in customers %}
        {% if (customer.location == 'dist1' and inventory_hostname == 'dist1-sw') or (customer.location == 'dist2' and inventory_hostname == 'dist2-sw') %}
        ! {{ customer.name }} Server Gateways
        interface vlan {{ customer.vlans.web }}
        description "{{ customer.name }} Web Servers Gateway"
        ip address {{ customer.networks.web | regex_replace('/24$', '') | regex_replace('\\.0$', '.1') }} 255.255.255.0
        no shutdown
        
        interface vlan {{ customer.vlans.app }}
        description "{{ customer.name }} App Servers Gateway"
        ip address {{ customer.networks.app | regex_replace('/24$', '') | regex_replace('\\.0$', '.1') }} 255.255.255.0
        no shutdown
        
        interface vlan {{ customer.vlans.db }}
        description "{{ customer.name }} DB Servers Gateway"
        ip address {{ customer.networks.db | regex_replace('/24$', '') | regex_replace('\\.0$', '.1') }} 255.255.255.0
        no shutdown
        
        ! {{ customer.name }} User Gateway
        interface vlan {{ customer.vlans.users }}
        description "{{ customer.name }} Users Gateway"
        ip address {{ customer.networks.users | regex_replace('/24$', '') | regex_replace('\\.0$', '.1') }} 255.255.255.0
        no shutdown
        {% endif %}
        {% endfor %}
        exit
        write memory

    - name: Configure Trunk Ports to Access Switches
      raw: |
        configure terminal
        {% if inventory_hostname == 'dist1-sw' %}
        ! Access Switch 연결 Trunk 설정
        interface FastEthernet0/1
        description "Trunk to access-sw1 (servers)"
        switchport mode trunk
        switchport trunk allowed vlan 100,101,102
        no shutdown
        
        interface FastEthernet0/2  
        description "Trunk to access-sw2 (users)"
        switchport mode trunk
        switchport trunk allowed vlan 200,201,202
        no shutdown
        {% elif inventory_hostname == 'dist2-sw' %}
        interface FastEthernet0/1
        description "Trunk to access-sw3 (servers)"
        switchport mode trunk
        switchport trunk allowed vlan 300,301,302
        no shutdown
        
        interface FastEthernet0/2  
        description "Trunk to access-sw4 (users)"
        switchport mode trunk
        switchport trunk allowed vlan 309
        no shutdown
        {% endif %}
        exit
        write memory

    - name: Enable IP Routing
      raw: |
        configure terminal
        ip routing
        exit
        write memory

    - name: Display Distribution Configuration
      debug:
        msg: |
          ===== {{ inventory_hostname }} 설정 완료 =====
          {% for customer in customers %}
          {% if (customer.location == 'dist1' and inventory_hostname == 'dist1-sw') or (customer.location == 'dist2' and inventory_hostname == 'dist2-sw') %}
          {{ customer.name }}:
          - Web VLAN: {{ customer.vlans.web }} ({{ customer.networks.web }})
          - App VLAN: {{ customer.vlans.app }} ({{ customer.networks.app }})
          - DB VLAN: {{ customer.vlans.db }} ({{ customer.networks.db }})
          - Users VLAN: {{ customer.vlans.users }} ({{ customer.networks.users }})
          {% endif %}
          {% endfor %}
