- name: Configure Distribution Switches - Updated Structure
  hosts: distribution
  gather_facts: no
  vars_files:
    - vars/customers.yml
  
  tasks:
    - name: Create Customer VLANs
      raw: |
        configure terminal
        {% for customer in customers %}
        {% if (customer.location == 'dist1' and inventory_hostname == 'dist1-sw') or (customer.location == 'dist2' and inventory_hostname == 'dist2-sw') %}
        vlan {{ customer.vlans.web }}
        name {{ customer.name }}-WEB-SERVERS
        vlan {{ customer.vlans.app }}
        name {{ customer.name }}-APP-SERVERS  
        vlan {{ customer.vlans.db }}
        name {{ customer.name }}-DB-SERVERS
        vlan {{ customer.vlans.users }}
        name {{ customer.name }}-USERS
        {% endif %}
        {% endfor %}
        exit
        write memory

    - name: Configure SVI Gateway Interfaces
      raw: |
        configure terminal
        {% for customer in customers %}
        {% if (customer.location == 'dist1' and inventory_hostname == 'dist1-sw') or (customer.location == 'dist2' and inventory_hostname == 'dist2-sw') %}
        interface vlan {{ customer.vlans.web }}
        description "{{ customer.name }} Web Servers Gateway"
        ip address {{ customer.networks.web | regex_replace('/24$', '') | regex_replace('\\.0$', '.1') }} 255.255.255.0
        no shutdown
        
        interface vlan {{ customer.vlans.app }}
        description "{{ customer.name }} App Servers Gateway"
        ip address {{ customer.networks.app | regex_replace('/24$', '') | regex_replace('\\.0$', '.1') }} 255.255.255.0
        no shutdown
        
        interface vlan {{ customer.vlans.db }}
        description "{{ customer.name }} DB Servers Gateway"
        ip address {{ customer.networks.db | regex_replace('/24$', '') | regex_replace('\\.0$', '.1') }} 255.255.255.0
        no shutdown
        
        interface vlan {{ customer.vlans.users }}
        description "{{ customer.name }} Users Gateway"
        ip address {{ customer.networks.users | regex_replace('/24$', '') | regex_replace('\\.0$', '.1') }} 255.255.255.0
        no shutdown
        {% endif %}
        {% endfor %}
        exit
        write memory

    - name: Configure Trunk Ports to Access Switches
      raw: |
        configure terminal
        {% if inventory_hostname == 'dist1-sw' %}
        ! Trunk to Access1 (CustomerA & CustomerB Servers)
        interface GigabitEthernet0/1
        description "Trunk to Access1 (Servers)"
        switchport mode trunk
        switchport trunk allowed vlan 100,101,102,200,201,202
        no shutdown
        
        ! Trunk to Access2 (CustomerA & CustomerB Users)
        interface GigabitEthernet0/2
        description "Trunk to Access2 (Users)"
        switchport mode trunk
        switchport trunk allowed vlan 109,209
        no shutdown
        
        {% elif inventory_hostname == 'dist2-sw' %}
        ! Trunk to Access3 (CustomerC Servers)
        interface GigabitEthernet0/1
        description "Trunk to Access3 (Servers)"
        switchport mode trunk
        switchport trunk allowed vlan 300,301,302
        no shutdown
        
        ! Trunk to Access4 (CustomerC Users)
        interface GigabitEthernet0/2
        description "Trunk to Access4 (Users)"
        switchport mode trunk
        switchport trunk allowed vlan 309
        no shutdown
        {% endif %}
        exit
        write memory

    - name: Enable IP Routing
      raw: |
        configure terminal
        ip routing
        exit
        write memory

    - name: Display Distribution Configuration
      debug:
        msg: |
          ===== {{ inventory_hostname }} Configuration Complete =====
          {% if inventory_hostname == 'dist1-sw' %}
          Distribution Switch 1:
          - Trunk g0/1 → Access1 (CustomerA & CustomerB Servers)
          - Trunk g0/2 → Access2 (CustomerA & CustomerB Users)
          - Gateway IPs configured for all customer VLANs
          {% elif inventory_hostname == 'dist2-sw' %}
          Distribution Switch 2:
          - Trunk g0/1 → Access3 (CustomerC Servers)
          - Trunk g0/2 → Access4 (CustomerC Users)
          - Gateway IPs configured for CustomerC VLANs
          {% endif %}
          
          Customer Networks:
          {% for customer in customers %}
          {% if (customer.location == 'dist1' and inventory_hostname == 'dist1-sw') or (customer.location == 'dist2' and inventory_hostname == 'dist2-sw') %}
          {{ customer.name }}:
          - Web VLAN: {{ customer.vlans.web }} ({{ customer.networks.web }})
          - App VLAN: {{ customer.vlans.app }} ({{ customer.networks.app }})
          - DB VLAN: {{ customer.vlans.db }} ({{ customer.networks.db }})
          - Users VLAN: {{ customer.vlans.users }} ({{ customer.networks.users }})
          {% endif %}
          {% endfor %}
