---
- name: OSPF | 동적 배포
  hosts: all
  gather_facts: no
  pre_tasks:
    - include_vars: { file: "vars/customers.yml", name: sot }
    - include_vars: { file: "vars/fabric.yml",   name: fab }

# Core: 지정 인터페이스만 un-passive + 네트워크 설정
- hosts: core
  gather_facts: no
  vars: { fab: "{{ hostvars['localhost'].fab }}" }
  tasks:
    - name: "Core OSPF 기본 설정"
      ios_config:
        parents: "router ospf {{ fab.ospf_process|default(1) }}"
        lines:
          - "router-id {{ fab.core.router_id }}"
          - "passive-interface default"

    - name: "Core OSPF 활성 인터페이스 설정"
      ios_config:
        parents: "router ospf {{ fab.ospf_process|default(1) }}"
        lines:
          - "no passive-interface {{ item }}"
      loop: "{{ fab.core.enable_if }}"

    - name: "Core OSPF 네트워크 설정"
      ios_config:
        parents: "router ospf {{ fab.ospf_process|default(1) }}"
        lines:
          - "network 10.0.1.0 0.0.0.255 area 0"
          - "network 10.0.0.0 0.0.0.3 area 0"
          - "network 10.0.2.0 0.0.0.255 area 0"

# Distribution: 동적 네트워크 기반 OSPF
- hosts: distribution
  gather_facts: no
  vars:
    sot: "{{ hostvars['localhost'].sot }}"
    fab: "{{ hostvars['localhost'].fab }}"
    my:  "{{ fab.dists[inventory_hostname] }}"
    loc: "{{ inventory_hostname | regex_replace('-sw$','') }}"
    custs: "{{ sot.customers | selectattr('location','equalto', loc) | list }}"
    srv_if: "{{ my.base_if[ sot.switch_mapping[loc].servers ] }}"
    usr_if: "{{ my.base_if[ sot.switch_mapping[loc].users ] }}"
      
  tasks:
    - name: "Distribution OSPF 기본 설정"
      ios_config:
        parents: "router ospf {{ fab.ospf_process|default(1) }}"
        lines:
          - "router-id {{ my.router_id }}"
          - "passive-interface default"
          - "no passive-interface {{ my.backbone_if }}"
          - "no passive-interface {{ srv_if }}"
          - "no passive-interface {{ usr_if }}"

    # 고객 네트워크를 동적으로 추가
    - name: "Distribution OSPF - 고객 네트워크 동적 설정"
      ios_config:
        parents: "router ospf {{ fab.ospf_process|default(1) }}"
        lines:
          - "network {{ item.base_network }} 0.0.255.255 area 0"
      loop: "{{ custs }}"
      
    # 백본 네트워크 설정
    - name: "Distribution OSPF - 백본 네트워크 설정" 
      ios_config:
        parents: "router ospf {{ fab.ospf_process|default(1) }}"
        lines:
          - "network 10.0.1.0 0.0.0.255 area 0"
          - "network 10.0.2.0 0.0.0.255 area 0"
