---
- name: QoS | 심플 MQC
  hosts: distribution
  gather_facts: no

  vars:
    sot: "{{ lookup('file','vars/customers.yml') | from_yaml }}"
    fab: "{{ lookup('file','vars/fabric.yml')    | from_yaml }}"
    loc: "{{ inventory_hostname | regex_replace('-sw$','') }}"
    my:  "{{ fab.dists[inventory_hostname] }}"
    custs: "{{ sot.customers | selectattr('location','equalto', loc) | list }}"
    srv_if: "{{ my.base_if[ sot.switch_mapping[loc].servers ] }}"
    usr_if: "{{ my.base_if[ sot.switch_mapping[loc].users ] }}"
    nets_web: "{{ custs | map(attribute='networks') | map(attribute='web') | list }}"
    nets_app: "{{ custs | map(attribute='networks') | map(attribute='app') | list }}"
    nets_db:  "{{ custs | map(attribute='networks') | map(attribute='db')  | list }}"

  tasks:
    - ios_config:
        save_when: modified
        lines: |
          ip access-list extended QOS_WEB
          {% for n in nets_web %}permit tcp {{ n.split('/')[0] }} 0.0.0.255 any eq 80
          permit tcp {{ n.split('/')[0] }} 0.0.0.255 any eq 443
          {% endfor %}
          ip access-list extended QOS_APP
          {% for n in nets_app %}permit tcp {{ n.split('/')[0] }} 0.0.0.255 any eq 443
          {% endfor %}
          ip access-list extended QOS_DB
          {% for n in nets_db %}permit tcp {{ n.split('/')[0] }} 0.0.0.255 any eq 3306
          permit tcp {{ n.split('/')[0] }} 0.0.0.255 any eq 5432
          {% endfor %}

    - ios_config:
        lines:
          - "class-map match-any CM_APP"
          - "match access-group name QOS_APP"
          - "class-map match-any CM_WEB"
          - "match access-group name QOS_WEB"
          - "class-map match-any CM_DB"
          - "match access-group name QOS_DB"
          - "policy-map PM_QOS"
          - "class CM_APP"
          - "priority percent 30"
          - "class CM_WEB"
          - "bandwidth percent 20"
          - "class CM_DB"
          - "bandwidth percent 10"
          - "class class-default"
          - "fair-queue"

    - ios_config:
        with_items:
          - "{{ srv_if }}"
          - "{{ usr_if }}"
        lines:
          - "interface {{ item }}"
          - "service-policy output PM_QOS"

